### ISSUE TITLE
createElement setting?

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#1074]
We allow `createClass` to be overridden with a [setting](https://github.com/yannickcr/eslint-plugin-react#configuration) - should we allow `createElement` to be configured as well?

If so, any rules referencing `React.createElement` should be sure to use `<pragma>.<createElement>`

**Comment by TrySound** [comment]
This works for me
```yml
settings:
  react:
    pragma: 'createElement'

rules:
  no-unused-vars: 'error'
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'
```
