### ISSUE TITLE
jsx-curly-spacing: [2, never] reports error for jsx inline comments

### ISSUE THREAD

**Issue by kentor** [yannickcr/eslint-plugin-react#165]
package.json
```json
{
  "dependencies": {
    "eslint": "^0.24.0",
    "eslint-plugin-react": "^3.0.0",
    "react": "^0.13.3"
  }
}
```

.eslintrc:
```yaml
---
ecmaFeatures:
  jsx: true
env:
  node: true
  es6: true
plugins:
  - react
rules:
  react/jsx-curly-spacing: [2, never]
  strict: 0
```

index.js:
```javascript
var React = require("react");

module.exports = React.createClass({
  render() {
    return <div>{/* comment */}</div>;
  }
});
```

```bash
❯ $(npm bin)/eslint index.js

index.js
  5:16  error  There should be no space after '{'   react/jsx-curly-spacing
  5:30  error  There should be no space before '}'  react/jsx-curly-spacing

✖ 2 problems (2 errors, 0 warnings)
```

Expected it not to report the error.
