### ISSUE TITLE
jsx-indent is not enforced on text

### ISSUE THREAD

**Issue by astorije** [yannickcr/eslint-plugin-react#1662]
Consider the following, minimal configuration of ESLint + `eslint-plugin-react `:

```yaml
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

rules:
  react/jsx-indent: error
```

and the following JSX file:

```jsx
import React from 'react';

export default function () {
    return (
        <div>
                    Test1

              <p>Test2</p>
        </div>
    );
}
```

The `Test2` line gets flagged correctly:

```
8:15  error  Expected indentation of 12 space characters but found 14  react/jsx-indent
```

But the `Test1` line passes the linter just fine. I looked at [the `jsx-indent` doc](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md) and it didn't say that indentation only applies to actual JSX elements and not to text.
Is that expected behavior, or a bug / false positive? If expected behavior, should the doc mention it?

*Apologies if there is already an issue about this, there are maaany opened issues about indentation and I might have skipped it if so.*
