### ISSUE TITLE
Variable are not properly marked as used when modules or globalReturn are enabled

### ISSUE THREAD

**Issue by MoOx** [yannickcr/eslint-plugin-react#18]
`src/widget.js`

```jsx
"use strict";

var React = require("react")
var HelloWorld = require("op/HelloWorld")

React.render(
  <div className="op-Widget">
    <HelloWorld />
  </div>,
  document.getElementById("op-Widget")
)
```

`.eslintrc`

```yaml
ecmaFeatures:
  modules: true
  # spread: true
  jsx: true

env:
  es6: true
  browser: true
  node: true

globals:
  __DEV__: true
  __PROD__: true

plugins:
  - react

# 0: off, 1: warning, 2: error
rules:
  # semicolons are useless
  semi: 0

  # @todo use the line below
  quotes: [2, "double"]

  # 2 spaces indentation,
  indent: [2, 2]

  # trailing coma are cool for diff
  comma-dangle: [2, "always"]

  # enforce comma at eol (never before)
  comma-style: [2, "last"]

  valid-jsdoc: 1

  # eslint-plugin-react rules
  react/no-multi-comp: 2
  react/prop-types: 2
  react/display-name: 2
  react/wrap-multilines: 2
  react/self-closing-comp: 2
  react/no-did-mount-set-state: 2
  react/no-did-update-set-state: 2
  react/jsx-uses-react: 2
  react/react-in-jsx-scope: 2

```

Gives

```console
$ eslint src/widget.js

src/widget.js
   8:4  error  HelloWorld is defined but never used     no-unused-vars
  11:2  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
  12:4  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
  12:5  error  'HelloWorld' is not defined              no-undef

✖ 4 problems (4 errors, 0 warnings)
```

What am I missing ?
