### ISSUE TITLE
Arrow function, PureComponent and prefer-stateless-function

### ISSUE THREAD

**Issue by swarthy** [yannickcr/eslint-plugin-react#903]
I write some error decorator.
If it returns like this, there is no problem:

``` javascript
import React, {PureComponent, PropTypes} from 'react'

export default function errorDecorator (options) {
  return WrappedComponent => {
    class Wrapper extends PureComponent {
      static propTypes = {
        error: PropTypes.string
      }
      render () {
        const {error, ...props} = this.props
        if (error) {
          return <div>Error! {error}</div>
        } else {
          return <WrappedComponent {...props} />
        }
      }
    }
    return Wrapper
  }
}
```

but with concise syntax I got error: 

``` javascript
export default function errorDecorator (options) {
  return WrappedComponent =>
    class Wrapper extends PureComponent { // Error: Component should be written as a pure function
      static propTypes = {
        error: PropTypes.string
      }
      render () {
        const {error, ...props} = this.props
        if (error) {
          return <div>Error! {error}</div>
        } else {
          return <WrappedComponent {...props} />
        }
      }
    }
}
```

UPD:
.eslintrc

``` yaml
parser: babel-eslint
env:
  browser: true
  node: true
plugins:
- react
extends:
- plugin:react/recommended
rules:
  react/prefer-es6-class:
  - 2
  - always
  react/prefer-stateless-function:
  - 2
  - ignorePureComponents: true
```
