### ISSUE TITLE
jsx-uses-vars rule doesn't work with ES6 class

### ISSUE THREAD

**Issue by sodatea** [yannickcr/eslint-plugin-react#96]
With `eslint@0.22.1` & `eslint-plugin-react@2.5.0`

`$ cat hello.jsx`
```jsx
class HelloMessage extends React.Component {
    static get propTypes() {
        return {
            name: React.PropTypes.oneOfType([
                React.PropTypes.string,
                React.PropTypes.number
            ])
        };
    }
    render() {
        return <div>Hello {this.props.name}</div>;
    }
}

React.render(<HelloMessage name='world' />, document.querySelector('#content'));
```

`$ cat .eslintrc`
```yaml
parser:
    babel-eslint

env:
    browser: true
    es6: true

plugins:
    - react

globals:
    React: true

rules:
    strict: 0
    quotes: [1, single, avoid-escape]
    indent: [1, 4]
    quote-props: [1, as-needed]
    no-unused-expressions: 1
    react/jsx-no-undef: 1
    react/jsx-quotes: [1, single, avoid-escape]
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
    react/prop-types: 1
    react/react-in-jsx-scope: 1
```

`$ eslint hello.jsx`
```
hello.jsx
  1:6  error  HelloMessage is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

Is that a bug of this plugin?
